<?php
// Widget chat for TrolyWP Agent Client
class TrolyWP_Agent_Client_Widget extends WP_Widget {
    public function __construct() {
        parent::__construct('trolywp_agent_client_widget', 'TrolyWP Agent Client Chat', [
            'description' => 'Widget chat AI TrolyWP',
        ]);
    }
    public function widget($args, $instance) {
        // Không làm gì ở đây, sẽ inject widget qua hook riêng để luôn hiển thị cho admin ở mọi trang.
    }
}

// Inject widget chat cho admin ở mọi trang (frontend/backend)
add_action('wp_footer', function() {
    if (!is_user_logged_in() || !current_user_can('manage_options')) return;
    $webhook_url = get_option('trolywp_agent_client_n8n_url', '');
    echo '<div style="padding:8px;font-size:12px;background:#f9f9f9;border-bottom:1px solid #eee;position:fixed;bottom:90px;right:24px;z-index:9999;">';
    echo 'Webhook URL: <b>' . esc_html($webhook_url) . '</b><br>';
    echo 'Option trạng thái: ' . (empty($webhook_url) ? '<span style="color:red">Rỗng</span>' : '<span style="color:green">Đã có</span>');
    echo '</div>';
    if (empty($webhook_url)) {
        echo '<div style="color:red;padding:12px;position:fixed;bottom:60px;right:24px;z-index:9999;">Chưa cấu hình webhook n8n URL!</div>';
    } else {
        echo '<div id="trolywp-chat-icon" style="cursor:pointer;width:60px;height:60px;background:#222;border-radius:50%;position:fixed;bottom:24px;right:24px;z-index:9999;display:flex;align-items:center;justify-content:center;box-shadow:0 2px 8px rgba(0,0,0,0.2);" title="TrolyWP Chat">\n            <svg width="32" height="32" fill="#fff" viewBox="0 0 24 24"><path d="M12 3C6.48 3 2 7.03 2 12c0 2.4 1.05 4.58 2.83 6.23-.13.49-.51 1.77-.73 2.47-.09.28.19.54.47.45.66-.21 2.02-.66 2.51-.81C8.7 21.66 10.31 22 12 22c5.52 0 10-4.03 10-9s-4.48-10-10-10zm0 17c-1.52 0-3.01-.29-4.37-.85l-.34-.14-.36.11c-.41.13-1.23.39-1.87.59.18-.56.47-1.51.57-1.89l.09-.36-.27-.28C4.13 16.13 3 14.17 3 12c0-4.42 4.03-8 9-8s9 3.58 9 8-4.03 8-9 8zm-1-7h2v2h-2v-2zm0-8h2v6h-2V5z"/></svg>\n        </div>';
        echo '<div id="trolywp-chat-panel" style="display:none;position:fixed;top:0;right:0;width:350px;height:100vh;background:#fff;border-radius:12px 0 0 12px;box-shadow:-2px 0 16px rgba(0,0,0,0.2);z-index:9999;overflow:hidden;transition:right 0.3s;">\n            <div style="position:relative;z-index:10000;display:flex;gap:8px;background:#f5f5f5;padding:8px 12px;border-bottom:1px solid #ddd;border-radius:12px 0 0 0;box-shadow:0 2px 8px rgba(0,0,0,0.08);width:100%;align-items:center;">\n                <button id="trolywp-chat-close" style="background:#eee;border:none;border-radius:50%;width:32px;height:32px;font-size:20px;cursor:pointer;box-shadow:0 1px 4px #ccc;">&times;</button>\n                <button id="trolywp-chat-mode-sidebar" style="background:#fff;border:1px solid #ccc;border-radius:6px;padding:0 12px;height:32px;font-weight:bold;cursor:pointer;box-shadow:0 1px 4px #ccc;">Sidebar</button>\n                <button id="trolywp-chat-mode-popup" style="background:#fff;border:1px solid #ccc;border-radius:6px;padding:0 12px;height:32px;font-weight:bold;cursor:pointer;box-shadow:0 1px 4px #ccc;">Popup</button>\n                <button id="trolywp-chat-mode-fixed" style="background:#fff;border:1px solid #ccc;border-radius:6px;padding:0 12px;height:32px;font-weight:bold;cursor:pointer;box-shadow:0 1px 4px #ccc;">Fixed</button>\n            </div>\n            <iframe id="trolywp-chat-iframe" src="' . esc_url($webhook_url) . '" style="width:100%;height:calc(100% - 56px);border:none;"></iframe>\n        </div>';
        echo '<script>\n        var icon = document.getElementById("trolywp-chat-icon");\n        var panel = document.getElementById("trolywp-chat-panel");\n        var closeBtn = document.getElementById("trolywp-chat-close");\n        var modeSidebar = document.getElementById("trolywp-chat-mode-sidebar");\n        var modePopup = document.getElementById("trolywp-chat-mode-popup");\n        var modeFixed = document.getElementById("trolywp-chat-mode-fixed");\n        var iframe = document.getElementById("trolywp-chat-iframe");\n        var currentMode = "sidebar";\n        // Lấy trạng thái từ localStorage khi mở panel\n        var savedMode = localStorage.getItem("trolywp_chat_mode");\n        if (savedMode) currentMode = savedMode;\n        function setMode(mode) {\n            currentMode = mode;\n            localStorage.setItem("trolywp_chat_mode", mode);\n            if (mode === "sidebar") {\n                panel.style.width = "350px";\n                panel.style.height = "calc(100vh - 32px)";\n                panel.style.top = "32px";\n                panel.style.right = "0";\n                panel.style.borderRadius = "12px 0 0 12px";\n                panel.style.boxShadow = "-2px 0 16px rgba(0,0,0,0.2)";\n                document.body.style.marginRight = "350px";\n            } else if (mode === "popup") {\n                panel.style.width = "350px";\n                panel.style.height = "420px";\n                panel.style.top = "auto";\n                panel.style.bottom = "90px";\n                panel.style.right = "24px";\n                panel.style.borderRadius = "12px";\n                panel.style.boxShadow = "0 2px 16px rgba(0,0,0,0.2)";\n                document.body.style.marginRight = "0";\n            } else if (mode === "fixed") {\n                panel.style.width = "100vw";\n                panel.style.height = "calc(100vh - 32px)";\n                panel.style.top = "32px";\n                panel.style.right = "0";\n                panel.style.borderRadius = "0";\n                panel.style.boxShadow = "none";\n                document.body.style.marginRight = "0";\n            }\n        }\n        icon.onclick = function(){\n            if (panel.style.display === "block") {\n                panel.style.display = "none";\n                document.body.style.marginRight = "0";\n            } else {\n                panel.style.display = "block";\n                setMode(currentMode);\n            }\n        };\n        closeBtn.onclick = function(){\n            panel.style.display = "none";\n            document.body.style.marginRight = "0";\n        };\n        modeSidebar.onclick = function(){ setMode("sidebar"); };\n        modePopup.onclick = function(){ setMode("popup"); };\n        modeFixed.onclick = function(){ setMode("fixed"); };\n        </script>';
    }
});
?>
